PL3/Controllers/AlumnoController.cs
//using Castle.Core.Configuration;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL3.Controllers
{
    public class AlumnoController : Controller
    {
        public ActionResult GetAll()
        {
            //instanciar servicio
            ML.Alumno alumno = new ML.Alumno();
            ServiceAlumno.AlumnosClient servicealumno = new ServiceAlumno.AlumnosClient();
            


            //Llamar al servicio
            var result = servicealumno.GetAll();



            if (result.Correct)
            {
                alumno.Alumnos = result.Objects.ToList();
            }
            else
            {
                ViewBag.Mensaje = "Ocurrio un error al consultar la información";
                return View();
            }
            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(byte? IdAlumno)
        {

            ML.Alumno alumno = new ML.Alumno();

            ML.Result resultAlumno = BL.Alumno.GetById(IdAlumno);

            if (resultAlumno.Correct)
            {
                alumno = (ML.Alumno)resultAlumno.Object;
            }
            if (IdAlumno == null)
            {

                return View(alumno);
            }
            else
            {
                ServiceAlumno.AlumnosClient servicealumno = new ServiceAlumno.AlumnosClient();
                var result = servicealumno.GetById(IdAlumno.Value);

                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                    return View(alumno);
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error al consultar la información";
                    return View();
                }
            }
        }
        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            if (alumno.IdAlumno == 0)
            {
                //result = BL.Alumno.Add(alumno);

                ServiceAlumno.AlumnosClient servicealumno = new ServiceAlumno.AlumnosClient();

                var result = servicealumno.Add(alumno);


                if (result.Correct)
                {
                    ViewBag.Message = "Se inserto correctamente el alumno";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al insertar el alumno";
                }
            }
            else
            {

                ServiceAlumno.AlumnosClient servicealumno = new ServiceAlumno.AlumnosClient();
                var result = servicealumno.Update(alumno);

                if (result.Correct)
                {
                    ViewBag.Message = "Se actualizo correctamente el alumno";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al actualizar el alumno";
                }
            }
            return PartialView("Modal");
        }
        public ActionResult Delete(ML.Alumno alumno)
        {
            ML.Result result = BL.Alumno.DeleteSP(alumno);
            if (result.Correct)
            {
                ViewBag.Message = "Se elimino el Departamento";

            }
            else
            {
                ViewBag.Message = "Ocurrio un error al eliminar el Departamento";
            }
            return PartialView("Modal");

        }
    }
}

PL3/Controllers/AlumnoMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace PL3.Controllers
{
    public class AlumnoMateriaController : Controller
    {
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = BL.Alumno.GetAll();

            alumno.Alumnos = result.Objects;

            return View(alumno);
        }
        [HttpGet]
        public ActionResult GetMateriasAsignadas(byte IdAlumno)
        {
            ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();

            ML.Result result = BL.AlumnoMateria.GetMateriasAsignadas(IdAlumno);
            ML.Result resultalumno = BL.Alumno.GetById(IdAlumno);

            alumnomateria.AlumnoMaterias = result.Objects;
            alumnomateria.Alumno = ((ML.Alumno)resultalumno.Object);

            return View(alumnomateria);
        }
        [HttpGet]
        public ActionResult GetMateriasNoAsignadas(byte IdAlumno)
        {
            ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();

            ML.Result result = BL.AlumnoMateria.GetMateriasNoAsignadas(IdAlumno);
            ML.Result resultalumno = BL.Alumno.GetById(IdAlumno);

            alumnomateria.AlumnoMaterias = result.Objects;
            alumnomateria.Alumno = ((ML.Alumno)resultalumno.Object);

            return View(alumnomateria);
        }
        public ActionResult Delete(ML.AlumnoMateria alumnomateria)
        {
            //ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();
            //alumnomateria.IdAlumnoMateria = IdAlumnoMateria;
            ML.Result result = BL.AlumnoMateria.DeleteMateriaAsignada(alumnomateria);

            ViewBag.MateriasAsignadas = true;
            ViewBag.IdAlumno = alumnomateria.IdAlumnoMateria;

            if (result.Correct)
            {
                ViewBag.message = "Se ha eliminado el registro";
            }
            else
            {
                ViewBag.message = "ocurrió un error al eliminar el registro " + result.ErrorMessage;

            }
            return PartialView("Modal");
        }
        [HttpPost]

        public ActionResult AddAlumnoMateria(ML.AlumnoMateria alumnomateria)
        {
            ML.Result result = new ML.Result();
            if (alumnomateria.AlumnoMaterias != null)
            {
                foreach (string IdMateria in alumnomateria.AlumnoMaterias)
                {
                    ML.AlumnoMateria alumnomateria1 = new ML.AlumnoMateria();

                    alumnomateria1.Alumno = new ML.Alumno();
                    alumnomateria1.Materias = new ML.Materia();

                    alumnomateria1.Alumno.IdAlumno = alumnomateria.Alumno.IdAlumno;
                    alumnomateria1.Materias.IdMateria = int.Parse(IdMateria);

                    ML.Result resul = BL.AlumnoMateria.AddAlumnoMateria(alumnomateria1);
                }
                result.Correct = true;
                ViewBag.Message = "Se ha actualizaron las materias";
                ViewBag.MateriasAsignadas = true;
                ViewBag.IdAlumno = alumnomateria.Alumno.IdAlumno;
            }
            else
            {
                result.Correct = false;
            }
            return PartialView("Modal");
        }
        public ActionResult DeleteAlumnoMateria(ML.AlumnoMateria alumnomateria)
        {
            ML.Result result = new ML.Result();
            if (alumnomateria.AlumnoMaterias != null)
            {
                foreach (string IdAlumnoMateria in alumnomateria.AlumnoMaterias)
                {
                    ML.AlumnoMateria alumnomateria1 = new ML.AlumnoMateria();

                    alumnomateria1.IdAlumnoMateria = int.Parse(IdAlumnoMateria);

                    ML.Result resul = BL.AlumnoMateria.DeleteMateriaAsignada(alumnomateria1);
                }
                result.Correct = true;
                ViewBag.Message = "Se ha actualizaron las materias";
                ViewBag.MateriasAsignadas = true;
                ViewBag.IdAlumno = alumnomateria.Alumno.IdAlumno;
            }
            else
            {
                result.Correct = false;
            }
            return PartialView("Modal");
        }
    }
}

PL3/Views/AlumnoMateria/GetAll.cshtml
@model ML.Alumno
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <section>

        <h1 class="text-center">Lista de Alumnos</h1>
        <p>
            En este modulo puedes visualizar los Alumnos existentes,<br />
            agregar, modificar y eliminar.
        </p>
    </section>
    <section>

        <div style="float:right;">
        </div>
    </section>
    <hr />
    <section>
        @if (Model.Alumnos == null)
        {
            <div class="row">
                <div class="alert alert-danger" role="alert">
                    @ViewBag.Message
                </div>
            </div>
        }
        else
        {
            <table class="table table-dark table-hover table-bordered table-responsive">
                <thead>
                    <tr>
                        <td class="text-center" style=" font-weight:bold;">Editar</td>
                        <td class="hidden">IdAlumno</td>
                        <td class="text-center" style="font-weight:bold;">Nombre</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Alumno alumno in Model.Alumnos)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-info bi bi-pencil-square" href="@Url.Action("GetMateriasAsignadas", "AlumnoMateria", new { IdAlumno = alumno.IdAlumno })"></a></td>
                            <td class="hidden">@alumno.IdAlumno</td>
                            <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </section>
</div>

PL3/Views/AlumnoMateria/GetMateriasAsignadas.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 text-center">
        <h2>Materias Asignadas</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("DeleteAlumnoMateria", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "hidden form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.Nombre)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.Nombre)
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.ApellidoPaterno)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoPaterno)
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.ApellidoMaterno)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoMaterno)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        <a class="btn btn-success glyphicon glyphicon-plus " href="@Url.Action("GetMateriasNoAsignadas", "AlumnoMateria", Model.Alumno)"></a>
                    </div>
                </div>
            </div>

            if (Model.AlumnoMaterias == null)
            {
                <table class="table table-dark table-hover table-bordered table-responsive">
                    <thead>
                        <tr>
                            <td class="text-center" style=" font-weight:bold;">El alumno no tiene materias asignadas</td>
                        </tr>
                    </thead>
                </table>
            }
            else
            {
                <table class="table table-dark table-hover table-bordered table-responsive">
                    <thead>
                        <tr>
                            <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                            <td class="hidden">IdAlumnoMateria</td>
                            <td class="hidden">IdMateria</td>
                            <td class="text-center" style="font-weight:bold;">Nombre</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.AlumnoMateria alumnomateria in Model.AlumnoMaterias)
                        {

                            <tr>
                                <td class="text-center">
                                    <input type="checkbox" value="@alumnomateria.IdAlumnoMateria" name="AlumnoMaterias">
                                </td>
                                <td class="hidden">@alumnomateria.IdAlumnoMateria</td>
                                <td class="hidden">@alumnomateria.Materias.IdMateria</td>
                                <td class="text-center">@alumnomateria.Materias.Nombre</td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            <div class="col">
                <input type="submit" value="Eliminar" class="btn btn-danger" />
                @Html.ActionLink("Regresar", "GetAll", "AlumnoMateria", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

PL3/Views/AlumnoMateria/GetMateriasNoAsignadas.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 text-center">
        <h2>Materias Sin Asignar</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("AddAlumnoMateria", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "hidden form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.Nombre)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.Nombre)
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.ApellidoPaterno)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoPaterno)
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Alumno.ApellidoMaterno)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoMaterno)
                    </div>
                </div>
            </div>
            <br>
            <br/>


            if (Model.AlumnoMaterias == null)
            {
                <table class="table table-dark table-hover table-bordered table-responsive">
                    <thead>
                        <tr>
                            <td class="text-center" style=" font-weight:bold;">El alumno tiene todas las materias asignadas</td>
                        </tr>
                    </thead>
                </table>
            }
            else
            {
                <table class="table table-dark table-hover table-bordered table-responsive">
                    <thead>
                        <tr>
                            <td class="text-center" style=" font-weight:bold;">Agregar</td>
                            <td class="hidden">IdMateria</td>
                            <td class="text-center" style="font-weight:bold;">Nombre</td>
                            <td class="text-center" style="font-weight:bold;">Costo</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.AlumnoMateria alumnomateria in Model.AlumnoMaterias)
                        {
                            <tr>
                                <td class="text-center">
                                    <input id="checkbox_@alumnomateria.Materias.IdMateria" type="checkbox" value="@alumnomateria.Materias.IdMateria" name="AlumnoMaterias" onclick="CalcularTotal(@alumnomateria.Materias.Costo, @alumnomateria.Materias.IdMateria)">
                                </td>
                                <td class="hidden">@alumnomateria.Materias.IdMateria</td>
                                <td class="text-center">@alumnomateria.Materias.Nombre</td>
                                <td class="text-center">@alumnomateria.Materias.Costo</td>

                            </tr>
                        }
                        <tr>
                            <td class="text-center">Total:</td>
                            <td></td>
                            <td id="total" class="text-center">0</td>
                        </tr>
                    </tbody>
                </table>
            }
            <br />
            <div class="col">
                <input type="submit" value="Guardar" class="btn btn-success" />
                @Html.ActionLink("Regresar", "GetmateriasAsignadas", "AlumnoMateria", Model.Alumno, htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>
<script type="text/javascript">
    function CalcularTotal(Costo, IdMateria) {
        if ($('#checkbox_' + IdMateria).is(':checked')) {
            var total = parseInt($('#total').text())
            total = total + Costo;
            $('#total').text(total)
        }
        else {
            var total = parseInt($('#total').text())
            total = total - Costo;
            $('#total').text(total)
        }
    }
</script>

PL3/Views/AlumnoMateria/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>