PL3/Controllers/MateriaController.cs
using Castle.Core.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;

namespace PL1.Controllers
{
    public class MateriaController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {

            ML.Materia materia = new ML.Materia();
            materia.Materias = new List<object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44389/api/");

                var responseTask = client.GetAsync("Materia/GetAll");
                responseTask.Wait(); //esperar a que se resuelva la llamada al servicio

                var result = responseTask.Result;


                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Materia resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                        materia.Materias.Add(resultItemList);
                    }
                }
            }
            return View(materia);
        }


        [HttpGet]
        public ActionResult Form(int? idMateria)
        {
            ML.Materia materia = new ML.Materia();
            //add
            if (idMateria == null)
            {
                return View(materia);
            }
            else //Update
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44389/api/");

                    var postTask = client.PostAsJsonAsync<int>("Materia/GetById", idMateria.Value);

                    postTask.Wait();

                    var result = postTask.Result;


                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<ML.Materia>();
                        readTask.Wait();
                        materia = readTask.Result;

                    }
                }
                return View(materia);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {

            ML.Result result = new ML.Result();
            if (materia.IdMateria == 0)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44389/api/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Add", materia);
                    postTask.Wait();

                    var materiaresult = postTask.Result;
                    if (materiaresult.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Se agrego correctamente el usuario";
                    }
                    else
                    {
                        ViewBag.Message = "Ocurrio un error al agregar el usuario";
                    }
                }
                return PartialView("Modal");
            }
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44389/api/");

                    //HTTP POST
                    var putTask = client.PutAsJsonAsync<ML.Materia>("Materia/Update", materia);
                    
                    putTask.Wait();

                    var materiaresult = putTask.Result;
                    if (materiaresult.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Se actualizo correctamente el usuario";
                    }
                    else
                    {
                        ViewBag.Message = "Ocurrio un error al actualizar el usuario";
                    }
                }
                return PartialView("Modal");
            }
        }


        public ActionResult Delete(int IdMateria)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44389/api/");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<int>("Materia/Delete", IdMateria);
                postTask.Wait();

                var materiaresult = postTask.Result;
                if (materiaresult.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se elimino correctamente el usuario";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al eliminar el usuario";
                }
            }
            return PartialView("Modal");
        }
    }
}

PL3/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12 text-center">
        <h2>Formulario Materias</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.IdMateria, new { @class = "hidden" })
                    @Html.TextBoxFor(model => model.IdMateria, new { @class = "hidden form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Nombre)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Nombre)
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Costo)
                    <div class="input-group">
                        <span class="input-group-addon"><i class="bi bi-person-circle"></i></span>
                        @Html.TextBoxFor(model => model.Costo, new { @class = "form-control", @id = "txtNombre" })
                        @Html.ValidationMessageFor(model => model.Costo)
                    </div>
                </div>
            </div>
            <br />
            <div class="col">
                <input type="submit" value="Guardar" class="btn btn-success" />
                @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

PL3/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <section>

        <h1 class="text-center">Lista de Materias</h1>
        <p>
            En este modulo puedes visualizar las Materias existentes,<br />
            agregar, modificar y eliminar.
        </p>
    </section>
    <section>

        <div style="float:right;">
            <div class="row">
                @Html.ActionLink("Agregar", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success bi bi-person-plus-fill" })
            </div>
        </div>
    </section>
    <hr />
    <section>
        @if (Model.Materias == null)
        {
            <div class="row">
                <div class="alert alert-danger" role="alert">
                    @ViewBag.Message
                </div>
            </div>
        }
        else
        {
            <table class="table table-dark table-hover table-bordered table-responsive">
                <thead>
                    <tr>
                        <td class="text-center" style=" font-weight:bold;">Editar</td>
                        <td class="hidden">IdMatera</td>
                        <td class="text-center" style="font-weight:bold;">Nombre</td>
                        <td class="text-center" style="font-weight:bold;">Costo</td>
                        <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (ML.Materia materia in Model.Materias)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form", "Materia", new { IdMateria = materia.IdMateria })"></a></td>
                            <td class="hidden">@materia.IdMateria</td>
                            <td>@materia.Nombre </td>
                            <td>@materia.Costo </td>
                            <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Materia", new { IdMateria = materia.IdMateria})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </section>
</div>